Pin protobuf to 3.20.1 for Anki 2.1.49
Google just released protobuf 4.21.0, which breaks Anki <= 2.1.49:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/_pytest/config/__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/_pytest/config/__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/_pytest/helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1016, in pytest_cmdline_parse
    self.parse(args)
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1304, in parse
    self._preparse(args, addopts=addopts)
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1187, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/pytest_anki/__init__.py", line 40, in <module>
    from ._session import AnkiSession  # noqa: F401
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/pytest_anki/_session.py", line 46, in <module>
    import anki.collection      # needed to avoid circular import error
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/anki/collection.py", line 10, in <module>
    from anki import (
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/anki/card_rendering_pb2.py", line 14, in <module>
    from anki import generic_pb2 as anki_dot_generic__pb2
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/anki/generic_pb2.py", line 28, in <module>
    _EMPTY = _descriptor.Descriptor(
  File "/home/runner/work/anki-delay-siblings/anki-delay-siblings/.tox/py38-anki2.1.49/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 313, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates